/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LiveStatusGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/twitch/controllers/get_live_status_controller.ts').default['render'], false>
}
type AdminDashboardGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/pages/controllers/pages_controller.ts').default['dashboard'], false>
}
type AdminArticlesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/articles/controllers/list_articles_controller.ts').default['render'], false>
}
type AdminArticlesCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/articles/controllers/store_article_controller.ts').default['render'], false>
}
type AdminArticlesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/articles/controllers/store_article_controller.ts').default['execute'], false>
}
type AdminArticlesIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/articles/controllers/update_article_controller.ts').default['render'], false>
}
type AdminArticlesIdPut = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/articles/controllers/update_article_controller.ts').default['execute'], false>
}
type AdminRedirectsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/redirects/controllers/list_redirects_controller.ts').default['render'], false>
}
type AdminRedirectsCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/redirects/controllers/store_redirect_controller.ts').default['render'], false>
}
type AdminRedirectsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/redirects/controllers/store_redirect_controller.ts').default['execute'], false>
}
type AdminRedirectsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/redirects/controllers/delete_redirect_controller.ts').default['execute'], false>
}
type AdminTaxonomiesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/taxonomies/controllers/list_taxonomies_controller.ts').default['render'], false>
}
type AdminTaxonomiesCategoriesCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/taxonomies/controllers/store_category_controller.ts').default['render'], false>
}
type AdminTaxonomiesCategoriesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/admin/taxonomies/controllers/store_category_controller.ts').default['execute'], false>
}
type OgComputeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/common/controllers/compute_og_image_controllers.ts').default['execute'], false>
}
type ArticlesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/articles/controllers/list_articles_controller.ts').default['render'], false>
}
type ArticlesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/articles/controllers/show_article_controller.ts').default['render'], false>
}
type ContactGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/controllers/contact_controller.ts').default['render'], false>
}
type AProposGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/pages/controllers/about_controller.ts').default['render'], false>
}
type LoginPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['execute'], false>
}
type LogoutDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/logout_controller.ts').default['handle'], false>
}
type ApiAssetsImagesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/media/controllers/upload_image_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'live': {
    'status': {
      '$url': {
      };
      '$get': LiveStatusGetHead;
      '$head': LiveStatusGetHead;
    };
  };
  'admin': {
    'dashboard': {
      '$url': {
      };
      '$get': AdminDashboardGetHead;
      '$head': AdminDashboardGetHead;
    };
    'articles': {
      '$url': {
      };
      '$get': AdminArticlesGetHead;
      '$head': AdminArticlesGetHead;
      'create': {
        '$url': {
        };
        '$get': AdminArticlesCreateGetHead;
        '$head': AdminArticlesCreateGetHead;
      };
      '$post': AdminArticlesPost;
      ':id': {
        'edit': {
          '$url': {
          };
          '$get': AdminArticlesIdEditGetHead;
          '$head': AdminArticlesIdEditGetHead;
        };
        '$url': {
        };
        '$put': AdminArticlesIdPut;
      };
    };
    'redirects': {
      '$url': {
      };
      '$get': AdminRedirectsGetHead;
      '$head': AdminRedirectsGetHead;
      'create': {
        '$url': {
        };
        '$get': AdminRedirectsCreateGetHead;
        '$head': AdminRedirectsCreateGetHead;
      };
      '$post': AdminRedirectsPost;
      ':id': {
        '$url': {
        };
        '$delete': AdminRedirectsIdDelete;
      };
    };
    'taxonomies': {
      '$url': {
      };
      '$get': AdminTaxonomiesGetHead;
      '$head': AdminTaxonomiesGetHead;
      'categories': {
        'create': {
          '$url': {
          };
          '$get': AdminTaxonomiesCategoriesCreateGetHead;
          '$head': AdminTaxonomiesCategoriesCreateGetHead;
        };
        '$url': {
        };
        '$post': AdminTaxonomiesCategoriesPost;
      };
    };
  };
  'og': {
    'compute': {
      '$url': {
      };
      '$get': OgComputeGetHead;
      '$head': OgComputeGetHead;
    };
  };
  'articles': {
    '$url': {
    };
    '$get': ArticlesGetHead;
    '$head': ArticlesGetHead;
    ':slug': {
      '$url': {
      };
      '$get': ArticlesIdGetHead;
      '$head': ArticlesIdGetHead;
    };
  };
  'contact': {
    '$url': {
    };
    '$get': ContactGetHead;
    '$head': ContactGetHead;
  };
  'a-propos': {
    '$url': {
    };
    '$get': AProposGetHead;
    '$head': AProposGetHead;
  };
  'login': {
    '$url': {
    };
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$delete': LogoutDelete;
  };
  'api': {
    'assets': {
      'images': {
        '$url': {
        };
        '$post': ApiAssetsImagesPost;
      };
    };
  };
}
const routes = [
  {
    params: [],
    name: 'live.status',
    path: '/live/status',
    method: ["GET","HEAD"],
    types: {} as LiveStatusGetHead,
  },
  {
    params: [],
    name: 'admin.pages.dashboard',
    path: '/admin/dashboard',
    method: ["GET","HEAD"],
    types: {} as AdminDashboardGetHead,
  },
  {
    params: [],
    name: 'admin.articles.index',
    path: '/admin/articles',
    method: ["GET","HEAD"],
    types: {} as AdminArticlesGetHead,
  },
  {
    params: [],
    name: 'admin.articles.create',
    path: '/admin/articles/create',
    method: ["GET","HEAD"],
    types: {} as AdminArticlesCreateGetHead,
  },
  {
    params: [],
    name: 'admin.articles.store',
    path: '/admin/articles',
    method: ["POST"],
    types: {} as AdminArticlesPost,
  },
  {
    params: ["id"],
    name: 'admin.articles.edit',
    path: '/admin/articles/:id/edit',
    method: ["GET","HEAD"],
    types: {} as AdminArticlesIdEditGetHead,
  },
  {
    params: ["id"],
    name: 'admin.articles.update',
    path: '/admin/articles/:id',
    method: ["PUT"],
    types: {} as AdminArticlesIdPut,
  },
  {
    params: [],
    name: 'admin.redirects.index',
    path: '/admin/redirects',
    method: ["GET","HEAD"],
    types: {} as AdminRedirectsGetHead,
  },
  {
    params: [],
    name: 'admin.redirects.create',
    path: '/admin/redirects/create',
    method: ["GET","HEAD"],
    types: {} as AdminRedirectsCreateGetHead,
  },
  {
    params: [],
    name: 'admin.redirects.store',
    path: '/admin/redirects',
    method: ["POST"],
    types: {} as AdminRedirectsPost,
  },
  {
    params: ["id"],
    name: 'admin.redirects.delete',
    path: '/admin/redirects/:id',
    method: ["DELETE"],
    types: {} as AdminRedirectsIdDelete,
  },
  {
    params: [],
    name: 'admin.taxonomies.index',
    path: '/admin/taxonomies',
    method: ["GET","HEAD"],
    types: {} as AdminTaxonomiesGetHead,
  },
  {
    params: [],
    name: 'admin.taxonomies.categories.create',
    path: '/admin/taxonomies/categories/create',
    method: ["GET","HEAD"],
    types: {} as AdminTaxonomiesCategoriesCreateGetHead,
  },
  {
    params: [],
    name: 'admin.taxonomies.categories.store',
    path: '/admin/taxonomies/categories',
    method: ["POST"],
    types: {} as AdminTaxonomiesCategoriesPost,
  },
  {
    params: [],
    name: 'og.compute',
    path: '/og/compute',
    method: ["GET","HEAD"],
    types: {} as OgComputeGetHead,
  },
  {
    params: [],
    name: 'pages.landing',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'articles.index',
    path: '/articles',
    method: ["GET","HEAD"],
    types: {} as ArticlesGetHead,
  },
  {
    params: ["slug"],
    name: 'articles.show',
    path: '/articles/:slug',
    method: ["GET","HEAD"],
    types: {} as ArticlesIdGetHead,
  },
  {
    params: [],
    name: 'pages.contact',
    path: '/contact',
    method: ["GET","HEAD"],
    types: {} as ContactGetHead,
  },
  {
    params: [],
    name: 'pages.about',
    path: '/a-propos',
    method: ["GET","HEAD"],
    types: {} as AProposGetHead,
  },
  {
    params: [],
    name: 'auth.login',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["DELETE"],
    types: {} as LogoutDelete,
  },
  {
    params: [],
    name: 'api.assets.store',
    path: '/api/assets/images',
    method: ["POST"],
    types: {} as ApiAssetsImagesPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
