enableTelemetry: false
nodeLinker: node-modules
npmMinimalAgeGate: '3d'

catalog:
  '@inertiajs/vue3': ^3.5.0
  '@tailwindcss/vite': ^4.3.0
  '@tuyau/core': ^1.2.2
  '@vitejs/plugin-vue': ^6.0.7
  '@vue/server-renderer': ^3.5.35
  tailwindcss: ^4.3.0
  typescript: ~5.9
  vite: ^7
  vue: ^3.5.35
