nodeLinker: pnpm

packageExtensions:
  "@formkit/auto-animate@*":
    peerDependencies:
      "vue": "*"
  "typescript-log@*":
    dependencies:
      "tslib": "*"
  "@adonisjs/logger@*":
    dependencies:
      "pino-pretty": "*"
