packages:
  - apps/*
  - packages/*

catalog:
  "@inertiajs/vue3": next
  "@julr/tooling-configs": ^2.2.0
  "@swc/core": ^1.7.26
  "@types/node": ^20.16.10
  eslint: ^8.57.1
  prettier: ^3.3.3
  typescript: ~5.6.2
  unocss: ^0.63.2
  vite: ^5.4.8
  vue-tsc: ^2.1.6
  vue: ^3.5.11
