packages:
  - apps/*
  - packages/*
catalog:
  '@inertiajs/vue3': next
  '@julr/tooling-configs': ^2.2.0
  '@swc/core': ^1.7.39
  '@tuyau/client': ^0.1.2
  '@tuyau/inertia': ^0.0.2
  '@types/node': ^20.17.0
  eslint: ^8.57.1
  prettier: ^3.3.3
  typescript: ~5.6.3
  unocss: ^0.63.6
  vite: ^5.4.10
  vue: ^3.5.12
  vue-tsc: ^2.1.6
