/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    articles: {
      ListArticles: () => import('#app/admin/articles/controllers/list_articles_controller'),
      PreviewOgImage: () => import('#app/admin/articles/controllers/preview_og_image_controller'),
      StoreArticle: () => import('#app/admin/articles/controllers/store_article_controller'),
      UpdateArticle: () => import('#app/admin/articles/controllers/update_article_controller'),
    },
    pages: {
      Pages: () => import('#app/admin/pages/controllers/pages_controller'),
    },
    redirects: {
      DeleteRedirect: () => import('#app/admin/redirects/controllers/delete_redirect_controller'),
      ListRedirects: () => import('#app/admin/redirects/controllers/list_redirects_controller'),
      StoreRedirect: () => import('#app/admin/redirects/controllers/store_redirect_controller'),
    },
    taxonomies: {
      ListTaxonomies: () => import('#app/admin/taxonomies/controllers/list_taxonomies_controller'),
      StoreCategory: () => import('#app/admin/taxonomies/controllers/store_category_controller'),
    },
  },
  articles: {
    ListArticles: () => import('#app/articles/controllers/list_articles_controller'),
    ShowArticle: () => import('#app/articles/controllers/show_article_controller'),
    ShowArticleOgImage: () => import('#app/articles/controllers/show_article_og_image_controller'),
  },
  auth: {
    Login: () => import('#app/auth/controllers/login_controller'),
    Logout: () => import('#app/auth/controllers/logout_controller'),
  },
  media: {
    UploadImage: () => import('#app/media/controllers/upload_image_controller'),
  },
  newsletter: {
    RegisterEmail: () => import('#app/newsletter/controllers/register_email_controller'),
  },
  pages: {
    About: () => import('#app/pages/controllers/about_controller'),
    Contact: () => import('#app/pages/controllers/contact_controller'),
    Landing: () => import('#app/pages/controllers/landing_controller'),
  },
  paste: {
    ShowPaste: () => import('#app/paste/controllers/show_paste_controller'),
    StorePaste: () => import('#app/paste/controllers/store_paste_controller'),
  },
  redirects: {
    ProcessRedirect: () => import('#app/redirects/controllers/process_redirect_controller'),
  },
  twitch: {
    GetLiveStatus: () => import('#app/twitch/controllers/get_live_status_controller'),
  },
}
