/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
