on:
  - pull_request
  - workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/iron", "latest"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - run: yarn

      - run: yarn workspace @rlanz/site lint
